config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get '/auth/spotify/callback', to: 'sessions#create'

  delete '/logout', to: "sessions#destroy"

  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show, :index]
  resources :playlists, only: [:index, :new, :create, :show, :edit, :update]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(
      provider: auth["provider"],
      name: auth["info"]["id"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update]

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(playlist_params)
    redirect_to playlist_path(@playlist)
  end

  def show
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to playlist_path(@playlist)
    else
      render :edit
    end
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist, only: [:new, :create]

  def index
    @songs = Song.all
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<div class="text-center">
<h1>Edit Artist</h1>
</div>

<%= render partial: "partials/form" %>

app/views/artists/index.html.erb
<div class="text-center">
  <h1>All Artists</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="btn btn-block button-coloring-one">
        <%= link_to "New Artist", new_artist_path %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <% @artists.each do |artist| %>
      <div class="col-md-3">
        <div class="text-center">
          <h4 class="artist-link"><%= link_to artist.name, artist_path(artist.id) %><br /></h4>
        </div>
      </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<div class="text-center">
  <h1>New Artist</h1>
</div>

<%= render partial: "partials/form" %>

app/views/artists/show.html.erb
<div class="text-center">
  <h1><%= @artist.name %></h1>
</div>

<br><br>

  <div class="row">
    <div class="col-md-3">
      <div class="btn btn-block button-coloring-one">
        <%= link_to "Edit #{@artist.name}'s information", edit_artist_path(@artist) %><br>
      </div>
      <br>
        <div class="text-center"><p> Edit to change the name of the artist or the display picture.<p></div>
    </div>

    <div class="col-md-3">
      <div class="btn btn-block button-coloring-two">
        <%= link_to "Delete #{@artist.name}", artist_path(@artist), method: :delete %><br>
      </div>
      <br>
      <div class="text-center"><p> Delete the artist from the database. </p>
        <p>...jerk</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="btn btn-block button-coloring-three">
        <%= link_to "Add a New Song by #{@artist.name}", new_artist_song_path(@artist) %><br>
      </div>
      <br>
      <div class="text-center"><p> Don't see a song you like from the artist?<p>
        <p>Add it to the database!</p>
      </div>
    </div>

      <div class="col-md-3">
        <%= image_tag @artist.image_path, style:"height: 250px; width: 250px;", class:"img-rounded" %>
      </div>
    </div>
  </div>
</div>

<br>

<div class="col-md-4 col-md-offset-5">
<div class="btn btn-default">
  <%= link_to "Back to Artists", artists_path %>
</div>
</div>

app/views/home/index.html.erb
<div class="container">
  <h1 class="text-center">Mix Master</h1>
</div>

<div class="well">
  <div class="row">

    <div class="col-md-4">
      <div class="btn btn-default btn-block">
        <h4><%= link_to "Playlists", playlists_path %></h4>
      </div>
      <div class="text-center">
        <br>
        <p> See a collection of the playlists others have made! </p>
        <p> Make your own playlists! </p>
      </div>
    </div>

    <div class="col-md-4">
      <div class="btn btn-default btn-block">
        <h4><%= link_to "Songs", songs_path %></h4>
      </div>
      <div class="text-center">
        <br>
        <p> See a collection of all the songs! </p>
      </div>
    </div>

      <div class="col-md-4">
        <div class="btn btn-default btn-block">
        <h4><%= link_to "Artists", artists_path %></h4>
      </div>
      <div class="text-center">
        <br>
        <p> See a collection of all the artists! </p>
        <p> Don't see your favorite? Add your own! </p>
        <p> Add songs to artists that totally exist! </p>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>

<%= render partial: "partials/header" %>

<div class="container">
  <%= yield %>
</div>

<%= render partial: "partials/footer" %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/partials/_checkboxes.html.erb
<%= form_for @playlist do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <% Song.all.each do |song| %>
    <div>
      <%= check_box_tag :song_ids, song.id, @playlist.songs.include?(song), name: 'playlist[song_ids][]', id: "song-#{song.id}" %>
      <%= song.title %>
    </div>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/partials/_error.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/partials/_footer.html.erb
<div class="container">
  <div class="footer-top-padding">
    <div class="text-center">
      <a class="footer-link" href="https://github.com/turingschool/lesson_plans/tree/master/ruby_02-web_applications_with_ruby/mix_master">Make Your Own!</a>

      <a class="footer-link" href="https://github.com/MsJennyGiraffe/mix_master">Github Repository</a>
    </div>
  </div>
</div>

app/views/partials/_form.html.erb
<%= form_for(@artist) do |form| %>
  <div class="text-center"><%= render partial: "partials/error", locals: { target: @artist } %></div>

<br>
  <div class="form-name-padding text-center">
    <%= form.label :name %>
  </div>

  <div class="text-center">
      <%= form.text_field :name %>
  </div>

  <div class="form-name-padding text-center">
    <%= form.label :image_path %>
  </div>

  <div class="text-center">
    <%= form.text_field :image_path %>
  </div>

<br><br>

  <div class="text-center">
    <%= form.submit %>
  </div>
  <% end  %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home<span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a href="#">Welcome, <%= current_user.name %></a></li>
          <li><%= link_to "Sign out", logout_path, method: :delete %></li>
        <% else %>
          <li><a href="/auth/spotify">Sign in with Spotify</a></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<%= render partial: "partials/checkboxes" %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>

<% @playlists.each do |playlist| %>
  <%= link_to playlist.name, playlist_path(playlist) %><br>
<% end %>

<%= link_to "New Playlist", new_playlist_path %><br>
<%= link_to "Home", root_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render partial: "partials/checkboxes" %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>

<ul>
  <% @playlist.songs.each do |song| %>
    <li> <%= link_to song.title, song %></li>
  <% end %>
</ul>

<%= link_to "Edit", edit_playlist_path(@playlist) %>

app/views/songs/index.html.erb
<div class="text-center">
<h1>Songs</h1>
</div>
<br><br>


<div class="container">
  <% @songs.each do |song| %>
      <div class="col-md-3">
        <div class="text-center">
          "<%= link_to song.title, song_path(song) %>" by <%= link_to song.artist.name, artist_path(song.artist) %><br><br />
        </div>
      </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<div class="text-center">
  <h1>New Song</h1>
</div>

<div class="text-center">
  <p>Add a new song for <%= @artist.name %></p>
</div>

<%= form_for([@artist, @song]) do |f| %>
  <div class="text-center">
    <%= f.label :title %>
  </div>
  <div class="text-center">
    <%= f.text_field :title %>
  </div>

  <div class="text-center">
    <br>
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/show.html.erb
<div class="text-center">
  <h1><%= @song.title %></h1>
</div>

<br>
<div class="text-center">
<p>This song brought to you by: <%= link_to @song.artist.name, artist_path(@song.artist) %></p>
</div>